let harvardSentences = 
[
	"La lampe de néon rouge irise ses cheveux.",
	"La nacelle du ballon tire sa souplesse de l’ osier.",
	"D evine qui a volé le précieux collier de jade.",
	"C’ est facile d’ atteindre la branche en sautant du muret.",
	"Ne collez jamais d’affiche sur le mur de la poste.",
	"D écoupe de fines lamelles de cette truffe noire.",
	"Une croisière dans un grand bateau, c’ est un bonheur parfait.",
	"Une brèche dans le mur laissait entrer de l’ air.",
	"Le groupe d’amis s’ est quitté devant le kiosque.",
	"La voiture de course partit en trombe sur la piste.",
	"Note sur le papier le poids de la bonbonne de gaz.",
	"Prends ce chiffon pour enlever la graisse de ton visage.",
	"La source de la rivière boueuse est un ruisseau clair.",
	"Tire la fléchette et inscris tes points sur le tableau.",
	"A ide la femme à monter à l’ arrière du tramway.",
	"Ils ont enfin trouvé une place à la crèche publique.",
	"L’ affaire reste étrange pour les vieux et les sages.",
	"Il a un cou propre sur un col net et soigné.",
	"Son dernier congé dura deux semaines.",
	"L’ idée est de coudre ensemble ces morceaux de tissus.",
	"Le lait de vache se compose surtout d’eau.",
	"Cueillez les roses puis coupez les épines.",
	"Le lièvre se distingue du lapin par ses pattes musclées.",
	"L’ envie d’écrire des histoires courtes est rare.",
	"La beauté de la vue a séduit toute la famille.",
	"Les poissons nageaient en rond dans le grand bocal.",
	"L’ homme remplit son sac de vieilles affaires.",
	"Le chêne est un arbre robuste qui donne de l’ ombre.",
	"Le gilet en laine n’ a ni poches, ni manches, ni revers.",
	"Le redoux à fait fermer les pistes de luge.",
	"L’ anse du cabas glisse de son épaule gauche.",
	"La souris évite les pièges posés sur son parcours.",
	"Fais la somme et reporte le total ici.",
	"R ejoins la chorale pour chanter le dernier couplet.",
	"Sens la faible chaleur de la flamme qui s’ éteint.",
	"Les épices rares viennent de l’ Extrême-Orient.",
	"L’ autel de marbre contraste avec les dalles en terre.",
	"Peins ce mur en violet pour un effet unique.",
	"L’ oie a été vendue pour un dîner qui s’ annonce grandiose.",
	"Le bourgeon de cette branche grandit chaque jour.",
	"Sautez du lit et prenez un café chaud.",
	"La musique restait forte pendant qu’ ils parlaient.",
	"Les jardins du château s’ étendent sur trois hectares.",
	"Le soleil au zénith fait briller le goudron.",
	"Elle secoue sa cape en marchant fièrement dans la rue.",
	"Pour ouvrir la clôture, soulève fort la poignée.",
	"La meute de loups se rassemble chaque nuit.",
	"Monte sur le muret et saute par-dessus la barrière.",
	"Plongez les biscuits secs dans l’ alcool pour qu’ ils s’ imbibent.",
	"Le grillage empêche les poussins de sortir de la cage.",
	"Un courant d’air glacé s’ engouffre dans le manteau.",
	"Le jeu de cartes s’ arrête au sixième pli.",
	"Un bon livre informe de ce que nous devons savoir.",
	"Le concert fut un fiasco dès le début.",
	"Une scie est un outil utile pour faire des planches.",
	"Les habits sèchent sur un support en bois mince.",
	"Respire avant de sauter et profite de l’ instant.",
	"Elle portait des boucles d’argent et un collier de nacre.",
	"Plante le rosier à côté des marches du perron.",
	"L’ année dernière nous vivions sur une péniche fleurie.",
	"Le combat prit fin en six minutes.",
	"Prenez un crayon à papier pour la première esquisse.",
	"D ommage que le poivre gâche ce ragoût de bœuf.",
	"Il a trouvé cette veste en laine pendant les soldes.",
	"Nous allons mettre fin à cette sinistre affaire.",
	"La maison de trois étages a été construite en pierre.",
	"Une nuée de moineaux volait dans le ciel d’orage.",
	"Il faudra beaucoup de courage pour vaincre son cancer.",
	"L’ île des tortues est visible depuis le bord de mer.",
	"La tâche d’encre a séché sur la page blanche.",
	"Bouchez le bocal avec ce couvercle en verre poli.",
	"Les plinthes sur la gauche du hall d’entrée se décollent.",
	"Le chat errant a mis bas hier.",
	"Les grues cendrées sont de grands oiseaux d’A frique.",
	"La jeunesse passe toujours tellement vite.",
	"L’ alarme stridente du réveil le tira de son sommeil.",
	"Le klaxon de la voiture réveille en sursaut le gendarme.",
	"C’ est la bonne saison pour partir marcher en montagne.",
	"À l’ ouest, les pruniers donnent peu de fruits.",
	"Les fausses perles brillent et coûtent peu.",
	"L’ armée a pris la place forte de l’ ennemi.",
	"Elle a surpris le chat du voisin sur le fauteuil du salon.",
	"Le prix est juste pour cette belle horloge antique.",
	"Le cheval a sauté et la barre de l’ obstacle est tombée.",
	"A joute une tasse de sucre roux à la recette.",
	"La grande maison avait des volets verts.",
	"Un calcul trop rapide augmente les erreurs.",
	"Pendant les fêtes, nous aimons la bonne cuisine.",
	"Les sourires de ce groupe d’enfants ont sauvé notre journée.",
	"Le crayon de papier est taillé mais la mine s’ est cassée.",
	"L’ ours brun est blessé par le piège du chasseur.",
	"Les lignes de fuite sont à peine visibles sur le plan.",
	"Le formol se conserve mieux en milieu humide.",
	"La nageoire du requin fendait l’ eau claire.",
	"Le dossard quatre a eu un faible score.",
	"Le ciment frais sécha pendant la nuit.",
	"Coupez le gâteau en quatre parts égales.",
	"L’ ivoire est prisé pour créer des bijoux de luxe.",
	"L’ eau de la source a des vertus sur la peau et les reins.",
	"La facture est payée toutes les trois semaines.",
	"Une zébrure de couleur marquait le rebord droit.",
	"C’ est ainsi, chats et chiens se haïssent depuis toujours.",
	"Ses études de chimie lui assurent un emploi rapide.",
	"Ouvrez la caisse en veillant à ne pas briser les verres.",
	"Le fromage suisse gagne en goût avec le temps.",
	"Il a neigé, plu et grêlé le même matin.",
	"Sept sceaux ont été posés sur de grandes feuilles.",
	"Lance la boule sur le couloir de bois vernis.",
	"La prochaine rencontre sportive a lieu demain.",
	"D éplace la cocotte en fonte sur le feu vif.",
	"L’ écorce du grand pin était brillante et sombre.",
	"Le canot en bouleau glissait sur l’ eau calme.",
	"La vache rousse dormait dans l’ herbe fraîche.",
	"Avoir vaut mieux que d’attendre et rêver.",
	"Le jus de citron fait de fameux cocktails.",
	"Il a mangé de la tarte aux pêches et une mousse au citron.",
	"Taille le tissu doré en fines bandes.",
	"Il essaye et s’ applique mais pourtant il s’ éloigne du but.",
	"Les nouvelles recrues ont droit au gîte et au couvert.",
	"Les choses simples donnent un plaisir pur.",
	"Un cri aigu perça le silence de la nuit.",
	"Le palmier est une plante qui pousse dans les régions chaudes.",
	"Le cheval flaire le sentier pour trouver le chemin.",
	"Ils chantaient les mêmes chansons à chaque fête.",
	"Les projets de loi ont été votés à la session d’automne.",
	"Ils arrivent à rire malgré la triste nouvelle.",
	"Le duc a quitté le parc dans un carrosse d’ argent.",
	"Il appuie son propos avec un tableau des dernières données.",
	"Les femmes de la tribu fabriquent et vendent des bijoux.",
	"La perte du second navire est un coup dur.",
	"Il a crié la même phrase trente fois.",
	"Manger bio aide à perdre du poids.",
	"Il s’ adonne à la couture pendant son temps libre.",
	"Il a vécu cinq ans avec un chien d’ aveugle.",
	"R aconte au chef tes soucis pour qu’ il puisse t’ aider.",
	"Les barbares ont pris le nord de la ville sans violence.",
	"Une telle force pourrait casser le mât.",
	"Il regrette la mauvaise tournure qu’ a prise la soirée.",
	"Il rompit net les liens avec son groupe d’amis.",
	"Le bus scolaire longe le lac gelé.",
	"D evine le score final du premier match.",
	"Il craint la façon dont le vent souffle.",
	"La juste cause a reçu le verdict qu’ elle mérite.",
	"Tends l’ oreille pour entendre les cigales de la pinède.",
	"Les caniches de pure race sont toujours bouclés.",
	"En partant maintenant du gymnase, il sera à l’ heure.",
	"Le bol en cuivre brillait aux rayons du soleil.",
	"Le bébé met son pied droit dans sa bouche.",
	"Il existe un écart certain entre penser et agir.",
	"Le plongeon de l’ athlète est loin d’ être parfait.",
	"Les enfants ont usé tous les crayons de la boîte.",
	"D’ épaisses lunettes lui ont permis de lire le livre.",
	"Il est passé devant sans que le jeune garçon ne le remarque.",
	"Il ne veut pas admettre ses petits tics de langage.",
	"Les coussins du sofa en cuir sont rouges et légers.",
	"La ligue de la paix discute de ses prochaines actions.",
	"Un roman d’amour est tombé du sac de sport.",
	"Faites-lui un prix pour cette table en marbre rose.",
	"Cette veste de soie blanche ira avec ses chaussures.",
	"Il a écrit son dernier roman à l’ hôtel du coin.",
	"L’ épais brouillard devrait freiner les chauffards.",
	"La teinte grise de la peinture du bureau est morne.",
	"Écoute cette chanson, elle évoque les vacances de Noël.",
	"La classe de yoga couvre la moitié de la plage.",
	"Une pluie de suie tombe du conduit chaud.",
	"La vapeur d’eau siffla de la vanne cassée.",
	"L’ enfant manqua de blesser le petit chien.",
	"La morue est la richesse première de ce drôle d’endroit.",
	"Brûle la tourbe et ajoute le bois de hêtre.",
	"D is-le avec douceur mais essaie d’être clair.",
	"Ce lundi matin est le pire moment pour se voir.",
	"Le courrier est livré en trois lots par jour.",
	"La nouvelle vendeuse a été virée hier midi.",
	"Le toit de la grange céda et tomba avec fracas.",
	"D épose à la banque la recette de la semaine passée.",
	"Cette mission spatiale explore une planète proche.",
	"Les fausses croyances se colportent toujours par des sceptiques.",
	"Huit hectares de forêt ont brûlé et sont perdus.",
	"Les voitures et les bus sont bloqués par les chutes de neige.",
	"Un jeune enfant ne devrait pas souffrir de faim.",
	"Les deux frères portent les mêmes baskets.",
	"La tasse cassée s’ est vidée sur la nappe en soie.",
	"Elle rédige un courriel à l’ enseigne pour se plaindre de l’ accueil.",
	"Des feuilles mortes jonchaient le sol en pierre.",
	"Les lois de la guerre régissent les statuts des otages.",
	"Les nouvelles circulent vite sur les réseaux sociaux.",
	"Sa chemise est propre mais le bouton du haut manque.",
	"Les élus du pays refusent de se risquer à une guerre.",
	"Le tour de manège a ravi tous les enfants.",
	"Un tapis rond couvre le plancher en bois.",
	"Les collants de grande taille sont durs à vendre.",
	"La place s’ emplit d’une foule houleuse et bruyante.",
	"Il refait son serment chaque mois de mars.",
	"Ce thé du japon a un léger goût sucré.",
	"Le papier est rare ici, donc écris avec soin.",
	"La pièce de monnaie antique était terne et usée.",
	"Avec du doigté les vrais verres en cristal chantent.",
	"Le savon flotte au-dessus de l’ eau du bain.",
	"Les feuilles mortes de l’ érable tombent sans bruit.",
	"Cette nouvelle pommade devrait faire des miracles.",
	"R etire ta veste d’hiver car la journée est douce.",
	"A près cette folle danse, ils sont rentrés à la maison.",
	"La terre sur ces légumes peut tâcher vos mains.",
	"Le potier surveille la cuisson des coupes en grès.",
	"L’ os du poignet était cassé et la main enflait.",
	"Les œuvres de ce peintre sont visibles dans deux galeries.",
	"L’ orage a surpris les enfants dans la cour du collège.",
	"Le bruit de la cloche marqua le début de la partie.",
	"Le toit de l’ abri a été conçu avec une forte pente.",
	"Essaye de tracer une fine ligne sur le tableau.",
	"Lave la nappe bleue qui couvre la table.",
	"La gouache est une peinture à l’ eau, couvrante et opaque.",
	"Note vite le code ou tu risques de le perdre.",
	"Le deuxième évier sert pour les grands plats.",
	"Elle recoud avec soin les trous du manteau usé.",
	"Le stylo à mine noire écrit mieux.",
	"Il s’ étend sur l’ herbe fraîche pour faire la sieste.",
	"Le plaignant a perdu l’ affaire face au juge.",
	"Le meuble massif à l’ entrée du salon était ciré.",
	"Le cheval a henni et le grand jockey est tombé.",
	"La mouche vole le long de la paroi en verre.",
	"L’ artiste observe la parade avec un œil inquiet.",
	"Les fans de twist aiment la musique rythmée.",
	"Il connaît les grandes qualités de la jeune actrice.",
	"Un manchon de fourrure est toujours doux et seyant.",
	"R emplis le seau de glaçons car ce vin est tiède.",
	"L’ équipe qui reste soudée sera la meilleure.",
	"La grêle tombait sur l’ herbe brune et brulée.",
	"La femelle paon est un oiseau fier et joli.",
	"Plie la carte pour pouvoir la ranger dans le sac.",
	"Les merlans sont des petits poissons qu’ on attrape au filet.",
	"La toile du fauteuil et des rideaux était bleue.",
	"L’ odeur âcre de l’ acide le prit à la gorge.",
	"Il faillit chuter au début du sentier des douaniers.",
	"Commande vite avant que le glacier ne ferme.",
	"Les larges bords du chapeau tombaient sur ses yeux.",
	"La cire épaisse protège le parquet des rayures.",
	"La mascotte de l’ équipe est un gros lynx roux.",
	"Le temps de la semaine nous réserve de nombreuses surprises.",
	"Il a couru sur le chemin menant à la nouvelle boutique.",
	"La petite boîte en papier est pleine d’épingles.",
	"Le corps de la parure est serti d’ une douzaine de saphirs.",
	"Le marais gèle quand il fait froid.",
	"L’ oiseau a laissé ses empreintes dans le ciment frais.",
	"Nous avons changé la pièce du moteur avec succès.",
	"L’ aube dardait un rayon doré sur le balcon.",
	"R egarde, les hommes marchent au milieu de la route.",
	"La cheville carrée est fixée au centre de la borne.",
	"Le quartier chinois est à côté du centre-ville.",
	"Le prince voulut qu’ on coupe la tête du voleur.",
	"Il a besoin d’aide pour finir le chantier à temps.",
	"Le mot d’ usage pour cet alcool local est gnôle.",
	"A joute la version finale à ta chaîne YouTube.",
	"Le fruit mauve du figuier a une forme de pomme.",
	"Les conserves de poire et de pêche manquent de saveur.",
	"C’ est une bande d’acier large de quinze mètres.",
	"D éplace la brouette de terre et vide-la ici.",
	"La grève du train a surpris et fâché les touristes.",
	"Ils étaient dehors quand le coup est parti.",
	"Sa réponse était claire et ils furent tous d’ accord.",
	"Les bombes ont laissé le centre de la ville en ruines.",
	"Elle est gentille et douce avec les personnes âgées malades.",
	"Il existe plusieurs manières de résoudre ce problème.",
	"Écris à cet ami cher une gentille lettre.",
	"Le vélo de l’ enfant glissa dans le chemin boueux.",
	"Nous avons quatre heures de travail intense.",
	"Cette cocotte en fonte est parfaite pour le civet de cerf.",
	"Les poissons et coraux ont souffert de la marée noire.",
	"Le pommeau de l’ épée protégeait sa main nue.",
	"La dette publique augmente chaque jour.",
	"Son large sourire séduit et trompe à la fois.",
	"Cette esquisse transmet bien l’ idée du courage.",
	"Emballe avec soin le violon et la flûte dans les étuis.",
	"Lisez la page à voix haute pour le public.",
	"La charnière sur la porte grinçait à cause de la rouille.",
	"Le vase doré est vraiment rare et coûteux.",
	"L’ odeur de chiffon brûlé agace son nez.",
	"Les deux marins ont perdu la vie dans la tempête.",
	"On n’ entend que le bruit du crissement des bottes sur la neige.",
	"La canne est l’ outil parfait pour pêcher le saumon.",
	"L’ hôtesse a montré le chemin aux convives de marque.",
	"Prenez un verre de jus de tomate pour changer.",
	"Veillez à loger la lampe dans le trou prévu.",
	"La sourdine permit de baisser le niveau sonore.",
	"A joute quinze au montant total de sa dette.",
	"La sauce brûlée a noirci le fond de la casserole.",
	"T ôt ce matin, le ciel était d’un gris soyeux.",
	"Emballe les paquets et n’ oublie pas de prendre le sel.",
	"Regarde la barque du pêcheur qui s’ éloigne sur le fleuve.",
	"Nourris la souris avec des graines et des tranches de fruit.",
	"Une fumée noire s’ échappe des fissures du tuyau.",
	"Retire du sol la bande de moquette usée.",
	"Le motard s’ est fait prendre par le radar fixe.",
	"Range la boîte à chaussure dans cet espace libre.",
	"A u printemps, la plante du balcon a poussé et fleuri.",
	"La poutre en chêne tomba sur la tête du maçon.",
	"Le boucher du coin a été volé la nuit dernière.",
	"La danseuse étoile avait la grâce d’un cygne.",
	"Les clous sur la chaussée crevèrent les pneus avant.",
	"La vieille horloge sur le mur indique midi.",
	"Il est rare en Espagne de manger de l’ autruche ou du serpent.",
	"Monte sur le podium et déclame ta tirade d’ un trait.",
	"Les chardons plient sous l’ effet du grand vent.",
	"L’ éclat de rire résonne dans la salle vide.",
	"Ce matin la baguette coûte moins cher.",
	"Cette star du football connaît un regain de succès.",
	"La joie se lit dans les yeux de la jeune fille.",
	"Le renard rôde encore autour des poules.",
	"Avant, les casques des pompiers étaient en laiton.",
	"V isse ce bouchon aussi serré que possible.",
	"Beaucoup de mains aident à faire le travail.",
	"La machine a rendu la monnaie en pièces de dix.",
	"La liste des noms est sculptée sur le pourtour du socle.",
	"Pour l’ envoi, emballe l’ objet avec du papier bulle.",
	"La perte du croiseur portait un coup à la flotte.",
	"A joute le sel avant de frire les œufs.",
	"Cette énigme se compose d’ une série de vers connus.",
	"Le glaçage de la bûche ravit les petits et les ados.",
	"Sers un thé chaud aux skieurs trempés.",
	"Le grenier de la maison rouge a pris feu.",
	"Les escrocs qui volent leurs amis méritent la prison.",
	"La coulée de boue a atteint le bord de la route.",
	"La banque le presse de payer l’ ensemble de ses dettes.",
	"Neuf rangées de soldats faisaient la file.",
	"Cette portion de la plage est sèche et couverte d’ algues.",
	"Le virus a détruit tous les fichiers texte.",
	"À ces mots l’ acteur devra quitter la scène.",
	"Il épargne de l’ argent en consommant très peu.",
	"Les points de lumière ont trahi le chat noir.",
	"Œufs pochés et jambon doivent suffire.",
	"La fille au comptoir a vendu cinquante billets.",
	"Le quai du port était visible depuis la fenêtre du salon.",
	"L’ espion reçut plusieurs messages d’Espagne.",
	"Les gélules rouges sont moins fortes que les autres.",
	"Le couteau tranchant était rangé dans son fourreau râpé.",
	"Un café noir aide à passer la soirée.",
	"Entoure cette figure avec des traits bleus épais.",
	"Des tribus nomades parcourent la steppe à cheval.",
	"D ès que le rideau s’ ouvre, tapez des mains.",
	"Naissance et mort marquent les limites de la vie.",
	"G ardez toujours la porte de la grange fermée.",
	"Le riz blanc est compris avec le plat de poulet.",
	"Mardi prochain, nous devons former le conseil.",
	"Verse une louche de potage dans chaque assiette.",
	"R epasse ces billets de banque mouillés pour les sécher.",
	"Cette figure de la mode s’ est fait connaître sur le net.",
	"L’ appât attire les truites et les carpes de l’ étang.",
	"Cet auteur a connu la censure pour trois de ses livres.",
	"Le bail de son studio est rompu depuis seize semaines.",
	"La fleur de lys est visible sur les blasons royaux.",
	"La banque déplore la faillite soudaine du commerce.",
	"La petite fille ôta vite son chapeau.",
	"Le vieux fermier semblait austère et seul.",
	"Va à la rencontre de ce groupe jovial de pêcheurs.",
	"Le thé infuse mal dans un pot froid.",
	"Il se rapproche du convoi tout en gardant de la distance.",
	"La clé est restée coincée dans la serrure du vestiaire.",
	"Le juge réclame une amende de mille dollars.",
	"Il est rare de nos jours de manger une cuisse de poulet.",
	"La brise marine est venue des dunes du nord.",
	"L’ aneth donne une saveur nordique à ce plat.",
	"Le rayon de bière a été vidé avant le match.",
	"Les pinces sont posées à côté du seau à glace.",
	"Les maisons sont construites en briques d’ argile rouge.",
	"Marque l’ endroit sur la carte avec un cercle rouge.",
	"La musique de ce film muet mérite un oscar.",
	"Les poils de chat et de chien le font tousser.",
	"Les personnes sensibles au pollen redoutent le printemps.",
	"Réveille-la sans la brusquer car la journée fut longue.",
	"La taille des poiriers se fait au milieu de l’ hiver.",
	"Couché sur le radeau, il bronzait dos au soleil.",
	"L’ affaire piétine et la famille attend toujours.",
	"Cet article n’ aborde qu’ une partie des enjeux réels.",
	"Fixez deux broches pour que cela tienne.",
	"La boule de pétanque a manqué de toucher son pied.",
	"V ivre à la montagne offre un air pur.",
	"Le succès du sandwich jambon salade est intact.",
	"Le cigare a laissé une marque sur le vernis du bureau.",
	"Les grappes de raisin ont été pressées pour faire du vin.",
	"Il fume la pipe et le cigare depuis trop longtemps.",
	"A joute quatre et sept et tu verras bien.",
	"La suite de l’ histoire est logique mais assez triste.",
	"A ppuie bien fort sur la pédale avec ton pied.",
	"Son plan de carrière échoue par manque de chance.",
	"C’ était un coup bas de la part du nouveau juge.",
	"Ces deux facteurs aident à comprendre la tendance.",
	"Le client propose un bon prix pour le lot.",
	"Le verrou de la remise doit rester fermé.",
	"Plonge treize minutes et remonte à la surface.",
	"L’ école enseigne aux élèves les bonnes manières.",
	"Ses plans pour l’ avenir étaient précis et censés.",
	"Les sachets de clous ont été triés par taille et par poids.",
	"Le bureau et deux chaises ont été peints en brun.",
	"G rille ces graines de courge, elles seront meilleures.",
	"Les lanternes violettes éclairent la pelouse sombre.",
	"Un kilo de farine coûte autant qu’ une mangue.",
	"La jeunesse conduit vite et manque de prudence.",
	"Pousse le cafard avec ce morceau de bois sec.",
	"Le tapis avait une large tache verdâtre.",
	"Le porto est un vin fort au goût fumé.",
	"Cette noix est trop dure, croque-la avec tes molaires.",
	"Il travaille le diamant pour sertir la bague de la mariée.",
	"R emplis ce bocal en verre de colle forte.",
	"Le petit chien a rongé et troué la chaussette.",
	"La perle a été montée sur un mince anneau d’ argent.",
	"Le thé du paquet bleu a un goût exquis.",
	"Les pieds des grands verres sont fendus ou cassés.",
	"Prends la poupée de chiffon pour ta petite nièce.",
	"Le molosse tira la laisse avec la force d’ un bœuf.",
	"Ouvrez votre livre d’histoire à la page douze.",
	"La boutique a fermé avant la fin de la vente.",
	"Pétris la pâte à pain et laisse-la lever.",
	"La fleur de la rose dure quelques jours.",
	"Il ramasse les dés et les jette pour une seconde partie.",
	"Ne monte pas dans le métro après le signal sonore.",
	"Ils prirent la hache et la scie pour aller en forêt.",
	"Une violente tempête a détruit le hangar de l’ usine.",
	"La cime de l’ arbre bougeait avec les rafales de vent.",
	"A u coucher du soleil, le ciel devient rose.",
	"Le printemps annonce le début de la saison des concours.",
	"Poster le paquet ce soir était une mauvaise idée.",
	"La région est aride mais regorge de richesses cachées.",
	"Une baleine à bosse a été vue près des côtes.",
	"L’ herbe et le lilas blanc sont mouillés par la rosée.",
	"Il prend tout son temps pour compter sa monnaie.",
	"Sans culture, la vie devient ennui et tristesse.",
	"Nos troupes vaillantes frappent de grands coups.",
	"L’ histoire raconte le mariage d’ un requin avec un dauphin.",
	"Le sens de l’ ouïe est plus fin que celui du toucher.",
	"G arde cette fiole pleine dans un lieu sûr.",
	"Sur l’ île, la brise marine est douce et légère.",
	"Le cuir est une matière qui demande des soins constants.",
	"Elle rougit quand il lui offrit un bouquet de tulipes.",
	"Les hommes conçoivent des plans mais agissent peu.",
	"Lève le marteau et tape d’un coup sec.",
	"Pour aller au lac prenez le chemin à gauche.",
	"La suture au front tiendra mais surveille cette plaie.",
	"Il tira un billet vert de sa poche gauche.",
	"Il préfère laver les draps à soixante degrés.",
	"Les branches du pommier sont tombées dans le ruisseau clair.",
	"La dalle a été taillée dans de lourds blocs de marbre.",
	"Les écailles de cette espèce de tortue sont pointues et rugueuses.",
	"Le drapeau du palais s’ agite avec la petite brise.",
	"La chemise en soie est sur le premier cintre de la penderie.",
	"Il s’ est trouvé coincé dans une foule compacte et bruyante.",
	"Tire fort la corde pour sonner la cloche.",
	"La lampe brillait d’une vive flamme verte.",
	"Ce message est le dernier signe de vie de son oncle.",
	"Les graines de fèves et de pois poussent dans des gousses.",
	"Un accent français a un charme étrange pour les A nglais.",
	"Nous avons vu le duo de jongleurs au cirque.",
	"La patte arrière s’ est coincée dans le piège rouillé.",
	"Il a sculpté une tête d’ homme dans le bloc en marbre.",
	"Une couche de neige gelée bordait la route.",
	"Le choix du texte de la préface importe peu.",
	"Le lézard se réchauffe sur la muraille de galets bruns.",
	"Il demande à son ami d’enfance de lui porter secours.",
	"Elle attend le taxi sur la pelouse devant l’ hôtel.",
	"Les derniers mots du discours laissent rêveur.",
	"Le civet a fini de cuire avant la nuit.",
	"Un plongeon dans l’ eau glacée restaure la santé.",
	"Les lionnes chassent en groupe et encerclent leur proie.",
	"La veste est posée sur le dossier du fauteuil de velours.",
	"L’ encre verte a fait une tâche sur le buvard.",
	"Les mites font des trous dans les habits en laine.",
	"La course à l’ atome s’ est soldée par un accord des parties.",
	"Le dernier mandat s’ est fini au mois de juin.",
	"Les crèmes brûlées ont été servies au goûter des enfants.",
	"Pris de panique, il s’ enfuit en courant et tomba.",
	"Les traces indiquent le chemin jusqu’ à la plage.",
	"Les palourdes se dégustent en automne sur la côte ouest.",
	"La muse du peintre habite derrière l’ église.",
	"Ouvrez la verrière de la cuisine pour que la vapeur s’ échappe.",
	"Une montre de luxe devrait plaire à tous.",
	"Sers encore du vin de Loire à nos convives.",
	"Malgré ses efforts, le jeune homme n’ est pas riche.",
	"Secoue la poussière de ce tapis aux motifs persans.",
	"Un silence soudain s’ abat sur la tribune nord.",
	"La malle noire est tombée durant le voyage.",
	"Un feu qui fume beaucoup chauffe peu.",
	"Le château de sable ne résiste pas à la montée des eaux.",
	"Le scout éclaire le fond de la tente avec son briquet.",
	"La première partie du plan doit changer.",
	"La reine des fourmis se régale d’une poire mûre.",
	"Il faisait son jogging dès le matin au réveil.",
	"L’ audace et la passion sont deux de ses nombreux talents.",
	"Observe les yeux du chat fixant la souris.",
	"Ce bras fort lui valut une médaille d’honneur.",
	"Enfonce le couteau dans le coin pour ouvrir l’ huître.",
	"Le vol du collier de perles a été tenu secret.",
	"Le parti jugea son programme trop flou.",
	"Ce ministre du travail excelle à prédire les grèves.",
	"Ses cheveux ont tendance à friser les jours de pluie.",
	"Les hommes du quart de nuit ont double paie.",
	"Le lin donne un tissu souple et robuste.",
	"Le navire français s’ est échoué sur les récifs coupants.",
	"La boîte est posée à côté du troisième camion.",
	"Mets le tableau sur le socle et oriente la lumière.",
	"Le skieur s’ est cassé le bras en tombant dans la crevasse.",
	"Les pétales vont tomber à la prochaine averse.",
	"La saison des soldes commence tôt cette année.",
	"Une lettre laissée sur le comptoir l’ emplit de bonheur.",
	"J ette les beignets de crevettes dans l’ huile bouillante.",
	"C’ est fâcheux que l’ affaire soit restée classée.",
	"Les gouttes de pluie font une douce musique.",
	"Ces vestiges romains ont été trouvés par un groupe de marcheurs.",
	"D emande à la cour de juger ce cas sensible.",
	"La poignée de la porte du buffet était en cuivre brillant.",
	"Ce matin il n’ arrivait pas à éteindre la machine à café.",
	"Les places de parking sont rares sur la rive nord.",
	"Ils se sont connus en T haïlande en jouant au volley sur le sable.",
	"La meilleure méthode est de la fixer au mur avec des punaises.",
	"Il a roulé sur son vélo le long de la route pentue.",
	"Il aime manger les steaks saignants de ce bistrot.",
	"Le lierre grimpait sur le piquet en bois de la clôture.",
	"Un petit ruisseau traverse le champ de seigle.",
	"L’ écorce du fruit a été coupée en tranches fines.",
	"Un départ rapide accroît les chances de gagner.",
	"Observe le joueur atteindre la troisième base.",
	"La levée des fonds a atteint son record mardi.",
	"La fissure du barrage grandit et menace la structure.",
	"Merci d’ ouvrir au client qui attend dans le hall.",
	"La boue a tâché le devant de sa chemise blanche.",
	"Un canal permet de passer d’ un fjord à l’ autre.",
	"Le jeune homme s’ enfuit par la porte du cellier.",
	"Un sentier raide est pénible pour nos pauvres pieds.",
	"Un trou rond creusait la roche de calcaire.",
	"La nouvelle jeta un doute dans les esprits des moines.",
	"Le cèdre fait de solides jouets en bois.",
	"La boîte en étain contient des pierres précieuses.",
	"A rrête de siffler et regarde les coureurs passer.",
	"Cette étoffe du nord de l’ Inde a perdu de son lustre.",
	"La vitrine du tailleur est remplie de robes longues.",
	"Enfile ce manteau en laine avant de sortir.",
	"Les êtres humains et les chevaux consomment de l’ avoine.",
	"R epasse la jupe et couds un bouton sur le gilet.",
	"Choisis une carte et mets-la en dessous du paquet.",
	"Un mortier est parfait pour broyer l’ ail et les herbes.",
	"Les légumes sautés sont exquis avec le jambon de pays.",
	"D imanche prochain est un jour très spécial.",
	"Le pauvre garçon a manqué le dernier bus.",
	"Il chargea la dernière cartouche du fusil et tira.",
	"Le lustre au plafond permet de lire tranquille.",
	"Le vote pour le nouveau drapeau commence demain.",
	"Le cycliste a sauté du podium d’ un bond léger.",
	"Hisse la valise sur le toit car le coffre est plein.",
	"Le bourdon bâtit son nid de mousse et d’ herbe.",
	"G lisse la facture du poêle entre ces deux feuilles.",
	"R éserve à l’ avance pour payer moins cher.",
	"Un chant étrange le stoppa net dans sa course.",
	"Il nouera la ficelle autour des sept livres.",
	"Un petit livre peut tenir dans la poche.",
	"Le dernier acte était confus et les acteurs minables.",
	"La brume opaque est créée par des feux de forêt.",
	"Son costume bordeaux avait dix ans.",
	"Les gousses de pois gourmands mûrissent dans les champs.",
	"Son fils aîné est inscrit en classe de théâtre.",
	"Il cueille des groseilles blanches pour le dessert de demain.",
	"Charge la tablette avant de prendre l’ avion.",
	"Il a laissé tomber son gant sur le rail du métro.",
	"Ce fromage s’ affine douze mois en cave.",
	"Il a prêté son manteau de ski au touriste transi.",
	"Ce problème technique risque de se produire à nouveau.",
	"Certaines annonces servent à tromper les clients.",
	"La corde entre le cheval et la charrette a rompu d’un coup.",
	"Elle présente un tailleur droit au salon de la mode.",
	"La drogue saisie hier est dans des sachets scellés.",
	"Le baudet tirait le panier en osier sur le sentier.",
	"Il mélange du jus de poire avec du vin blanc.",
	"Le fermier a troqué son cheval pour un bœuf brun.",
	"Écope la coque du bateau pour ne pas couler à pic.",
	"L’ opale est une pierre précieuse aux vertus magiques.",
	"Boucle ton lacet de gauche et remonte ton short.",
	"La mousse verte pousse à la lisière du bois.",
	"Ce film raconte la vie d’ un danseur de tango.",
	"Il a donné l’ ordre de répondre vite aux appels.",
	"À l’ automne, les feuilles des arbres brunissent et jaunissent.",
	"Les pales de l’ hélice fendaient le nuage dense.",
	"Les faits ne montrent pas toujours assez qui a raison.",
	"La mule marcha la nuit entière sur les sentiers.",
	"La vaisselle s’ est cassée au sol avec grand fracas.",
	"Secoue la poussière du tapis sur le talus de la pelouse.",
	"Mettez la barrière et fermez la porte de la grange.",
	"Le fils du meunier broie la récolte d’avoine.",
	"Le riz est souvent servi dans des bols ronds.",
	"Le chaton fuit devant le chien de chasse.",
	"Un pari osé peut mener à la ruine.",
	"La bière est faite d’ eau, de malt et de houblon.",
	"Fais trois copies de la liste des commandes.",
	"Un juré têtu plaide une cause perdue.",
	"Quelle joie, nos vieux amis arrivent ce midi.",
	"Le hangar de stockage a pris feu dans la nuit.",
	"Un savon doux donne une peau parfaite.",
	"Cette planche est assez solide pour marcher dessus.",
	"Les cris du bébé lui mettent les nerfs en pelote.",
	"Les cartes marines sont précises mais manquent de couleur.",
	"Les pièces tombaient de la foule et roulaient partout.",
	"Sa nouvelle voiture de fonction a une rayure sur le coffre.",
	"Le ciel à l’ ouest est teinté de rouge sanglant.",
	"Le cochon a rampé sous la haute clôture du jardin.",
	"Le pot a bouilli, mais la pâte n’ a pas vraiment gonflé.",
	"Pars déjà si tu ne veux pas rentrer tard.",
	"Mets ce sac de charbon au fond de la cave.",
	"Il a donné les figues mais a gardé les cerises mûres.",
	"Les veaux savourent l’ herbe tendre du printemps.",
	"À chaque fois, ils repoussent les attaques de l’ ennemi.",
	"Prends le briquet et frotte-le contre ta chaussure.",
	"Lance la fléchette dans le mille de la cible de liège.",
	"Les joueuses russes dominent le tournoi de volley.",
	"Ces pièces seront utiles pour payer sa dette.",
	"Monte le chauffage, la pièce manque de chaleur.",
	"Avec un vol de nuit vous ne perdrez pas trop de temps.",
	"L’ absence d’efforts à fournir semblait le réjouir.",
	"La bretelle étroite débouche sur l’ entrée de la rocade.",
	"Elle porte la veste de tailleur avec grande classe.",
	"Prends le siège et explique aux autres la consigne.",
	"Le voilier de plaisance navigue au milieu de la baie.",
	"Les cochons sont nourris avec du maïs haché et des ordures.",
	"Le club n’ accepte que les paiements par carte visa.",
	"Nous avons besoin de foin pour nourrir les mules.",
	"Les remparts cernent le bourg et assurent la défense.",
	"Les pirates ont volé les riches touristes du bateau.",
	"Le jeune docteur l’ a guéri de son mal avec des gélules.",
	"La grille devant le feu protège des flammes.",
	"Nous avons un nouveau service d’ envoi du courrier.",
	"Le filet tendu a freiné la chute de l’ homme.",
	"Le rideau rouge se lève et le spectacle commence.",
	"La ceinture de soie égaye sa robe courte.",
	"Prenez votre chapeau pour la troisième marche de la saison.",
	"Le nid en paille contient cinq merles.",
	"Les fougères brunes aiment un climat humide.",
	"À l’ époque un roi était à la tête de l’ état français.",
	"Creuse profond dans la terre pour trouver le trésor.",
	"Les baskets et les tongs sont bannies de ce club privé.",
	"Un bagage en toile prendra moins d’espace.",
	"Congèle l’ eau pour faire de nouveaux glaçons.",
	"Souriez quand vous dites des mots méchants.",
	"Le vrai et le juste sont des valeurs d’essence divine.",
	"Le coup de pioche fit jaillir une pépite.",
	"Les roues du chariot grinçant ont besoin d’huile.",
	"Ce jeu de cartes semble pénible et stupide.",
	"Le gardien retourne de vacances dimanche soir.",
	"Le repère de la crue est dix mètres au-dessus.",
	"Tournez la vanne pour faire sortir la vapeur.",
	"La javel permet de laver à fond les sols.",
	"Le conseil hésite mais décide toujours à la fin.",
	"A ccroche les clochettes avec soin autour des branches.",
	"Les mangas se lisent mieux à la plage qu’ en voiture.",
	"Chauffer les épices à la poêle exalte leur saveur.",
	"Ses paupières se ferment par manque chronique de sommeil.",
	"A rrête et regarde l’ homme qui travaille dur.",
	"Éponge l’ eau versée avec le chiffon à carreaux.",
	"Colle la feuille sur le mur bleu foncé.",
	"À présent les cassettes sont absentes des rayons de musique.",
	"Le crachin et la bruine sont pire qu’ une pluie battante.",
	"La glace à la menthe a givré le bol à punch.",
	"La critique acclame de nouveau son dernier film.",
	"L’ express du soir part toujours à l’ ouest.",
	"Les méandres du tunnel prennent fin bientôt.",
	"Tous sont assis figés devant l’ écran.",
	"Le papier rouge brilla dans la scène sombre.",
	"Ils étaient heureux de voir la régate au port.",
	"Les rues sont étroites et pleines de virages serrés.",
	"L’ athlète grimpe avec aisance la falaise de calcaire.",
	"Les jeunes commandent souvent leurs habits en ligne.",
	"Ils découpent la saucisse fine avec un couteau denté.",
	"L’ homme portait une plume à son chapeau de feutre.",
	"Une jument grise marchait devant le poulain.",
	"Les croissants chauds c’ est un délice avec un café brûlant.",
	"Les bouteilles contiennent quatre sortes de rhum.",
	"Les clowns du cirque d’ hiver sont tristes mais drôles.",
	"La grippe l’ a cloué à la maison trois semaines.",
	"D épose les cendres sur le vieux tapis usé.",
	"Le crapaud et la grenouille chantent sur la même note.",
	"J etez la tasse et l’ assiette en plastique sale.",
	"Une odeur piquante et poivrée emplit l’ air.",
	"Le chien aide le berger qui rassemble ses bêtes.",
	"Le jeudi est le bon jour pour faire du shopping.",
	"L’ alarme murale sonne fort et souvent.",
	"Fends la bûche avec un fort coup de hache.",
	"Mettez la lanterne qui donne beaucoup de lumière.",
	"Le tuyau arrose le gazon chaque soir.",
	"Ce geste de la main signale la fin du jeu.",
	"A ide-le à ouvrir le couvercle de ce bocal d’ asperges.",
	"Remplis le porche avec des nattes de paille tressée.",
	"Le but du concours est de lever de grands fonds.",
	"Le club a loué la salle pour cinq nuits.",
	"L’ air humide déforme les planches de bois.",
	"La prise de courant est au format standard du pays.",
	"Presse-toi si tu souhaites partir tôt ce soir.",
	"Il était cloué au sol et ne pouvait pas bouger ses jambes.",
	"Même neuf, le tuyau se mit à rouiller.",
	"Une chaise en plastique a glissé du camion de transport.",
	"L’ oiseau volait libre dans le vent chaud.",
	"A ide à tisser le côté droit du tapis.",
	"La venue d’ une crampe est un sérieux risque en mer.",
	"Le forain surveille le manège d’un regard distrait.",
	"Il quitta la salle en colère et frappa la porte.",
	"Prenez refuge sous cette tente le temps de l’ averse.",
	"Nous ne touchons pas beaucoup d’argent mais nous rions bien."
];
