let harvardSentences = 
[
	[
	"Esse tema foi falado no congresso.",
	"Leila tem um lindo casaco.",
	"O analfabetismo é um problema chato.",
	"O casarão foi vendido sem pressa.",
	"Agindo com união ainda rende mais.",
	"Recebi meu pai pra almoçar.",
	"O trabalho é a vida do povo.",
	"Isso se resolverá de maneira tranquila.",
	"Os pesquisadores não acreditam nessa história.",
	"Sei que amanhã atingiremos a meta proposta."
	],
	[
	"Nosso telefone está mudo.",
	"Desculpe se te chamo de velho.",
	"Queremos discutir o orçamento.",
	"Ela não tem fome quando sai de casa.",
	"Uma índia andava na floresta.",
	"Zeca, corra bem rápido pra casa.",
	"Neste caso, donnirei tranquilo.",
	"João deu dinheiro pro seu pai comprar um jogo.",
	"Ainda faltam seis minutos.",
	"Ela seguia discretamente."
	],
	[
	"Eu vi logo a índia Joana e o Léo.",
	"João caminhou na praia cahna.",
	"Vi Zé fazer essas viagens seis vezes.",
	"O atabaque do Tito é coberto com pele de gato.",
	"Ele dorme num leito de palha.",
	"Paira um ar de arara amarela no Rio.",
	"Foi muito difícil entender a canção de natal.",
	"Depois do almoço te encontro pro chá.",
	"Esses são nossos timezinhos.",
	"Procurei Maria em casa."
	],
	[
	"A pesca é proibida nesse canto.",
	"Quero te ver bem quando ele voltar de lá.",
	"Tenho muito orgulho de nossa gente.",
	"O inspetor faz a vistoria completa.",
	"Ainda não se sabe o dia da prova.",
	"Será muito dificil conseguir que eu coma.",
	"A paixão dele é a natureza.",
	"Você quer me dizer a data?.",
	"Desculpe, mas me atrasei no casamento.",
	"Faz um desvio em direção ao mar."
	],
	[
	"O velho tigre ainda aceita combate.",
	"É hora do homem se humanizar mais.",
	"Ela ficou na fazenda por uma hora.",
	"Seu crime foi encoberto pelo capataz.",
	"A escuridão do quarto assustou a criança.",
	"Hoje, eu não pude fazer minha ginástica.",
	"Comer quindim é sempre tuna boa pedida.",
	"Hoje irei precisar de você.",
	"Sem ele o tempo flui num ritmo suave.",
	"A sujeira lançada no rio contamina os peixes."
	],
	[
	"Ojogo será transmitido à tarde.",
	"É possível que ele já esteja fora de perigo.",
	"A explicação pode ser encontrada na tese.",
	"Meu vôo tinha sido marcado para as cinco horas.",
	"Daqui a pouco a gente vai ao baile.",
	"Estou certo que mereço a atenção dela.",
	"Era um belo enfeite todo de palha.",
	"O comércio daqui é bem tranquilo.",
	"É a minha chance de esclarecer a notícia.",
	"A visita transfonnou-se numa reunião."
	],
	[
	"O cenário da história é um subúrbio da cidade.",
	"Eu tenho uma ótima razão pra festejar.",
	"A pequena nave medirá o campo magnético.",
	"O prêmio será entregue na sessão solene.",
	"A ação se passa numa cidade cahna.",
	"Ela e seu namorado chato saem do carro.",
	"O adiantamento surpreendeu a mim e a todos.",
	"A gente sempre colhe o que plantou.",
	"Aqui é onde existe a ﬂor mais interessante.",
	"A corrida de invemo foi uma alegria."
	],
	[
	"Esse empreendimento terá grande sucesso.",
	"A feira livre não funcionará amanhã.",
	"Fumar é prejudicial à saúde e é feio.",
	"Entre com seu velho código e o número da conta.",
	"Reﬂita antes e discuta depois.",
	"A aula dele é bastante charmosa.",
	"Usar mais aditivo pode ser desastroso.",
	"O clima não é mau em Calcutá.",
	"A locomotiva vem com mais carga.",
	"Ainda é uma boa temporada pro cinema."
	],
	[
	"Os maiores picos da Terra ﬁcam debaixo da água.",
	"A inauguração da vila é quarta ou quinta-feira.",
	"Vote se você tiver o título de eleitor.",
	"Hoje é ﬁmdamental encontrar a razão da existência humana.",
	"A temperatura é mais amena à noite.",
	"Em muitas cidades a população está diminuindo.",
	"Nunca se deve ﬁcar em cima do morro.",
	"Para as pessoas estranhas o panorama é desolador.",
	"É bom te ver colhendo ﬂores, menino!.",
	"Eu finjo me banhar num lago ao amanhecer."
	],
	[
	"É de fundamental importância encontrar uma solução comum.",
	"A previsão é de muito nevoeiro no Rio.",
	"Os móveis virão as cinco da tarde.",
	"O barraco pode desabar em algumas horas.",
	"O candidato falou como se já estivesse eleito.",
	"A idéia é falha, mas interessante.",
	"O dia está bom pra passear de navio.",
	"Minha correpondência me espera em casa.",
	"A saída pra crise dele é o diálogo.",
	"Finalmente São Pedro chamou o mau tempo."
	],
	[
	"Um casal de gatos come no telhado.",
	"A cantora foi apresentar um grande sucesso.",
	"Lá é um lugar ótimo pra tomar uns chopinhos.",
	"O musical consumiu quatro meses da vida da gente.",
	"O baile começa após às nove horas.",
	"Apesar desse resultado tomarei uma decisão.",
	"A verdade não poupa nem as celebridades.",
	"O frio deve diminuir ainda este ano.",
	"O vão da plataforma é estreito.",
	"Infelizmente não fui a ginástica."
	],
	[
	"Os meninos prenderam um filhote de tigre.",
	"A bolsa de valores está em alta.",
	"O congresso volta atrás em sua palavra.",
	"A médica receitou que eles mudassem de clima.",
	"Não é permitido fumar no interior do ônibus.",
	"A garota foi presa naquela noite.",
	"O prato do dia é couve no tempero.",
	"Eu viajarei a Belém amanhã.",
	"A balsa é o meio de transporte daqui.",
	"A apresentação foi cancelada por causa da chuva."
	],
	[
	"O grêmio ganhou uma quadra de esportes.",
	"Hoje irei à vila sem meu ﬁlho.",
	"Essa chuva não ocorre mais todo ano.",
	"Será bom que ele estude o assunto.",
	"O menu inclui um prato muito saboroso.",
	"Podia dizer as horas por gentileza?.",
	"A casa é enfeitada com rosas.",
	"A Terra é farta mas não inﬁnita.",
	"O sinal emitido é captado pelos receptores.",
	"A mensalidade aumentou mais que a inflação."
	],
	[
	"O tele-jornal começa às dez da noite.",
	"A cabine do telefone ﬁca na próxima rua.",
	"Defender a ecologia é manter a vida.",
	"Nesse verão o calor é insuportável.",
	"O jardim exige muito trabalho.",
	"O pão que eu comprei era ótimo.",
	"Meu pai se entenderá com o padre chato amanhã.",
	"Durante o dia apague a luz.",
	"A sociedade unlguaia tem que se mobilizar.",
	"Nossas atitudes são calmas."
	],
	[
	"Dezenas de cabos eleitorais buscavam apoio.",
	"Nunca uma vitória foi paga com tanto suor.",
	"Nosso ﬁlho ama os animais.",
	"Esse peixe é mais letal que algumas cobras.",
	"O time continua lutando pelo sucesso.",
	"Essa medida foi devidamente alterada.",
	"O estilete é uma anna perigosa.",
	"Me aguarde, quinta-feira eu venho jantar em casa.",
	"A mudança é lenta porém duradoura.",
	"O clima não é mais seco no interior."
	],
	[
	"Sua sensibilidade mostrará o caminho.",
	"A Amazônia é a reserva ecológica do globo.",
	"O ministério mudou demais com a eleição.",
	"Novas metas surgem na informática.",
	"O capital de uma empresa depende de produção.",
	"Se não fosse ela, tudo teria sido melhor.",
	"A principal personagem no ﬁlme é uma gueixa.",
	"Espere seu amigo em casa.",
	"A juventude tinha que revolucionar a escola.",
	"A cantora terá quatro meses pra ensaiar seu canto."
	],
	[
	"Prazer em conhecê-los.",
	"Elas traziam o equipamento.",
	"O sol ilumina 0 planeta.",
	"A correção do exame foi coerente.",
	"O vidro é antigo mas o armário, não.",
	"O natal deve ser um dia alegre.",
	"Trabalhei mais do que podia.",
	"Hoje eu acordei calmo.",
	"Esse canal parece bastante chato.",
	"Nem parece que nós nascemos aqui."
	],
	[
	"Receba minha prima na festa.",
	"Ela planejou um grande banquete cheio de gente.",
	"No lado de cá do rio há uma boa sombra.",
	"A maioria dos visitantes gosta deste momento.",
	"Minha ﬁlha é especialista em música sacra.",
	"A casa só tem um quarto.",
	"A duração do simpósio é de cinco dias.",
	"Ao contrário de nossa expectativa, tudo foi tranquilo.",
	"A intenção é ter o apoio do governante.",
	"A ﬁla aumentou ao longo do dia."
	],
	[
	"À noite, a temperatura deve ir a zero.",
	"A proposta foi inspecionada pela gerência.",
	"Os quadros azuis mostram o codidiano.",
	"Já era tarde, quando ele me abordou.",
	"O canário canta ao amanhecer.",
	"A lojinha não ﬁca na esquina.",
	"Meu bom time se consagrou como o melhor.",
	"O instituto deve servir a sua meta.",
	"Ele não entende, nem quando se fala pausadamente.",
	"Seu limite do cheque azul foi aumentado."
	],
	[
	"O termômetro indicava o calor.",
	"O discurso de abertura tem que ser longo.",
	"Eu precisei de tempo na conferência.",
	"Zeca marcou a temporada de jogos.",
	"Nada como um almoço ao ar livre.",
	"Nossa ﬁlha éa primeira da classe.",
	"Gostaria de chamar meu pai.",
	"Não tive uma prova cansativa.",
	"Ainda tenho cinco telefonemas pra dar.",
	"Os hotéis do sudoeste são fantásticos."
	]
];
